/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\door\DOOR_V2.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DOOR_V2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 2.559]}>
        <mesh geometry={nodes.Mesh_35.geometry} material={materials.brown2} />
        <mesh geometry={nodes.Mesh_35001.geometry} material={materials.brown2} position={[0, 0, -1.74]} />
        <mesh geometry={nodes.Mesh_35002.geometry} material={materials.brown2} position={[0, 0, 2.835]} />
        <mesh geometry={nodes.Mesh_35003.geometry} material={materials.brown2} position={[0, 0, -2.861]} />
        <mesh geometry={nodes.Mesh_35004.geometry} material={materials.brown2} position={[0, 0, -1.418]} />
      </group>
      <group position={[0, 0, 2.559]}>
        <group position={[0, 0, -1.74]}>
          <mesh geometry={nodes.Mesh_80001_1.geometry} material={materials.Baked_B_2} />
          <mesh geometry={nodes.Mesh_80001_2.geometry} material={materials.grey} />
        </group>
      </group>
      <group position={[0, 0, 2.559]}>
        <mesh geometry={nodes.archibd___Door_lock___P___1003.geometry} material={materials.Blackhandle} position={[0, 0, -1.74]} />
        <group position={[0, 0, -1.74]}>
          <mesh geometry={nodes.Mesh_89001.geometry} material={materials.Blackhandle} />
          <mesh geometry={nodes.Mesh_89001_1.geometry} material={materials.numberkey} />
        </group>
        <mesh geometry={nodes.archibd___Door_lock___P___3003.geometry} material={materials.Blackhandle} position={[0, 0, -1.74]} />
        <mesh geometry={nodes.archibd___Door_lock___P___4003.geometry} material={materials.Blackhandle} position={[0, 0, -1.74]} />
        <mesh geometry={nodes.archibd___Door_lock___P___1002.geometry} material={materials.Blackhandle} position={[0, 0, -1.74]} />
        <mesh geometry={nodes.archibd___Door_lock___P___3002.geometry} material={materials.Blackhandle} position={[0, 0, -1.74]} />
        <mesh geometry={nodes.archibd___Door_lock___P___4002.geometry} material={materials.Blackhandle} position={[0, 0, -1.74]} />
        <mesh geometry={nodes.archibd___Door_lock___P___5001.geometry} material={materials.Blackhandle} position={[0, 0, -1.74]} />
        <mesh geometry={nodes.archibd___Door_lock___P___6001.geometry} material={materials['Archibd _ Brushed Matel _ 2']} position={[0, 0, -1.74]} />
      </group>
      <mesh geometry={nodes.tttttt001.geometry} material={materials.Baked_B_4} position={[0.165, -0.184, -5.135]} />
      <mesh geometry={nodes.ttttttt001.geometry} material={materials.Baked_B_3} position={[-2.231, -0.184, -5.135]} />
      <mesh geometry={nodes.tttt001.geometry} material={materials.Baked_B_6} position={[5.333, -0.184, -5.135]} />
      <mesh geometry={nodes.ttt001.geometry} material={materials.Baked_B_5} position={[2.667, -0.184, -5.135]} />
      <mesh geometry={nodes.ttttttt002.geometry} material={materials.Baked_B_2} position={[-4.468, -0.184, -5.135]} />
    </group>
  )
}

useGLTF.preload('/DOOR_V2.gltf')
