/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\door\DOOR_V3.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DOOR_V3.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.819]}>
        <mesh geometry={nodes.Mesh_80001.geometry} material={materials.Baked_B_2} />
        <mesh geometry={nodes.Mesh_80001_1.geometry} material={materials.grey} />
      </group>
      <group position={[0, 0, 0.819]}>
        <mesh geometry={nodes.Mesh_88001.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.Mesh_88001_1.geometry} material={materials.numberkey} />
      </group>
      <mesh geometry={nodes.tttttt001.geometry} material={materials.Baked_B_4} position={[0.165, -0.184, 0.179]} />
      <mesh geometry={nodes.ttttttt001.geometry} material={materials.Baked_B_3} position={[-2.231, -0.184, 0.179]} />
      <mesh geometry={nodes.tttt001.geometry} material={materials.Baked_B_6} position={[5.333, -0.184, 0.179]} />
      <mesh geometry={nodes.ttt001.geometry} material={materials.Baked_B_5} position={[2.667, -0.184, 0.179]} />
      <mesh geometry={nodes.ttttttt002.geometry} material={materials.Baked_B_2} position={[-4.468, -0.184, 0.179]} />
    </group>
  )
}

useGLTF.preload('/DOOR_V3.gltf')
