/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\door\Door2.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Door2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.root.geometry} material={materials.brown}>
        <mesh geometry={nodes.Mesh_0.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_79.geometry} material={materials.brown} />
        <mesh geometry={nodes.archibd___Door_lock___P___1001.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.archibd___Door_lock___P___3001.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.archibd___Door_lock___P___4001.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.Mesh_89.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.Mesh_89_1.geometry} material={materials.numberkey} />
        <mesh geometry={nodes.archibd___Door_lock___P___1.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.archibd___Door_lock___P___3.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.archibd___Door_lock___P___4.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.archibd___Door_lock___P___5.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.archibd___Door_lock___P___6.geometry} material={materials['Archibd _ Brushed Matel _ 2']} />
        <mesh geometry={nodes.Mesh_36.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_37.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_38.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_39.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_40.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_41.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_42.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_43.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_44.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_45.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_46.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_47.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_48.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_49.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_50.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_51.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_52.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_53.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_54.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_55.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_56.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_57.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_58.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_59.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_60.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_61.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_62.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_63.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_64.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_65.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_66.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_67.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_68.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_69.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_70.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_71.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_72.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_73.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_74.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_75.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_76.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_77.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_78.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_10.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_11.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_12.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_13.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_14.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_15.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_16.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_17.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_18.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_19.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_20.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_21.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_22.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_23.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_24.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_25.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_26.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_27.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_28.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_29.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_30.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_31.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_32.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_33.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_34.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_35.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_7.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_8.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_9.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_1_1.geometry} material={materials.grey} />
        <mesh geometry={nodes.Mesh_1_2.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_80.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_81.geometry} material={materials.brown} />
        <mesh geometry={nodes.Mesh_82.geometry} material={materials.brown} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Door2.gltf')
