/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\door\door.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Door(props) {
    const { nodes, materials } = useGLTF('./door/door.gltf')
    return (
      <group {...props} dispose={null} position={[0, 0, -10]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials['default material']} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={materials['0133_Gray']} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={materials['0017_IndianRed']} />
        <mesh geometry={nodes.mesh_0_3.geometry} material={materials['0133_Gray']} />
        <mesh geometry={nodes.mesh_0_4.geometry} material={materials['Archibd _ Black Brushed Matel _ 3.jpg']} />
        <mesh geometry={nodes.mesh_0_5.geometry} material={materials['Archibd _ Brushed Matel _ 2']} />
        <mesh geometry={nodes.mesh_0_6.geometry} material={materials['archibd _ Door Wood _1']} />
        <mesh geometry={nodes.mesh_0_7.geometry} material={materials['Archibd _ White Brushed Matel _ 4.jpg']} />
      </group>
    )
}

useGLTF.preload('./door/door.gltf')
