/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\door\twoUntitled.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/twoUntitled.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_92.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_92_1.geometry} material={materials['archibd _ Door Wood _1']} />
      <mesh geometry={nodes.mesh_92_2.geometry} material={materials.grey} />
      <mesh geometry={nodes.mesh_0.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_79.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_2.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_3.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_4.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_5.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_6.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_7.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_8.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_9.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_10.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_11.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_12.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_13.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_14.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_15.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_16.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_17.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_18.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_19.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_20.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_21.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_22.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_23.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_24.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_25.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_26.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_27.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_28.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_29.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_30.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_31.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_32.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_33.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_34.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_35.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_36.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_37.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_38.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_39.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_40.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_41.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_42.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_43.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_44.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_45.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_46.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_47.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_48.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_49.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_50.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_51.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_52.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_53.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_54.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_55.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_56.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_57.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_58.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_59.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_60.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_61.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_62.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_63.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_64.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_65.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_66.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_67.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_68.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_69.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_70.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_71.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_72.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_73.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_74.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_75.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_76.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_77.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_78.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_80.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_81.geometry} material={materials.brown} />
      <mesh geometry={nodes.mesh_82.geometry} material={materials.brown} />
      <mesh geometry={nodes.archibd___Door_lock___P___1.geometry} material={materials.Blackhandle} />
      <mesh geometry={nodes.archibd___Door_lock___P___5.geometry} material={materials.Blackhandle} />
      <mesh geometry={nodes.archibd___Door_lock___P___6.geometry} material={materials['Archibd _ Brushed Matel _ 2']} />
      <mesh geometry={nodes.archibd___Door_lock___P___3.geometry} material={materials.Blackhandle} />
      <mesh geometry={nodes.archibd___Door_lock___P___4.geometry} material={materials.Blackhandle} />
      <mesh geometry={nodes.archibd___Door_lock___P___1_1.geometry} material={materials.Blackhandle} />
      <mesh geometry={nodes.archibd___Door_lock___P___3_1.geometry} material={materials.Blackhandle} />
      <mesh geometry={nodes.archibd___Door_lock___P___4_1.geometry} material={materials.Blackhandle} />
      <mesh geometry={nodes.mesh_89.geometry} material={materials['archibd _ Door Wood _1']} />
      <mesh geometry={nodes.mesh_89_1.geometry} material={materials.Blackhandle} />
      <mesh geometry={nodes.mesh_89_2.geometry} material={materials.numberkey} />
    </group>
  )
}

useGLTF.preload('/twoUntitled.gltf')
